import {
  Anvil,
  Bird,
  BrickWall,
  Castle,
  Cat,
  Coins,
  Cog,
  Crown,
  Dog,
  Feather,
  Flame,
  Gem,
  GraduationCap,
  Hammer,
  Mountain,
  PawPrint,
  Pickaxe,
  Rabbit,
  Sparkles,
  Store,
  Swords,
  Target,
  TowerControl,
  TreePine,
  Trees,
  Warehouse,
  Wheat,
  Worm,
  type LucideIcon,
} from 'lucide-react'
import type { CrestSymbol } from './types'

/** Иконки, на которые ссылаются данные ресурсов и зданий (поле icon) */
export const GAME_ICONS: Record<string, LucideIcon> = {
  Coins,
  TreePine,
  Mountain,
  Anvil,
  Wheat,
  Gem,
  Castle,
  Swords,
  Target,
  Rabbit,
  Hammer,
  Cog,
  Sparkles,
  GraduationCap,
  Pickaxe,
  Store,
  Warehouse,
  BrickWall,
  TowerControl,
}

/** Геральдические символы гербов (приближение; Часть 5 заменит на SVG-геральдику) */
export const CREST_SYMBOL_ICONS: Record<CrestSymbol, LucideIcon> = {
  wolf: Dog,
  hawk: Bird,
  dragon: Flame,
  stag: Trees,
  bear: PawPrint,
  serpent: Worm,
  lion: Crown,
  raven: Feather,
  boar: Mountain,
  fox: Cat,
}
